# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Asvoria Kuan Soo Huey
title: Homo sapiens...
email: asvoria@live.com
phone: "+6016-4713138"
cv   : "resume.pdf"
website: https://asvoria.github.io/MyCV/

# Social links
#twitter_username: jekyllrb
github_username:  asvoria
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: asvoriakuan
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
whatsapp_number: "60164713138"
researchgate_name: Soo-Huey-Kuan

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Engineer with strong technical knowledge and hands on experience. Over 12 years working in the electronics industry. Started her own electronic product business, build up a product. Electronics hardware from architecture, schematic, simulation, PCB floorplanning, routing, BOM, assembly, testing, FA, to final documentation of her invention. Also profess in IC desgin, from RTL to schematics, to mask/layout design of 14nm (or less) technology. Also an expert in C/C++/C# programming. She believes all computer languages are the same! Regardless of java python solidity or any new languages that a computer may understand: codes.

    - <a href='#projects'> Current Projects </a>
    - <a href='#xprojects'> Previous Projects </a>
    - <a href='#employment'> Employment History </a>
    - <a href='#education'> Education Background </a>
    - <a href='#extra'> Other Infromation </a>
    - [Download My Resume](https://moya10.github.io/awesome-cv/resume.pdf)

# Projects Section
projects_title: Current Projects #(Use this to override about projects section title)

# Experience Section
experience_title: Employment History #(Use this to override about experience section title)

# Education Section
education_title: Education Background #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  **Skills**
  * Programming - expert in C/C++/C# but flexible on all other programming languages. An advocate for the concept of teaching C as "Mother of all programming languages". Profess both firmware and software programming.
  * Electronics circuit design (both digital and analogue circuits), from schematic to PCBA.
  
  **Interests**
  * [Art](http://avichenatelier.blogspot.com/)

  **Obligation**
  * [Charity Fund](https://asvoria.github.io/olmcf/)

  **Experiment**
  * [Thrifty Old Student Experimental Projects](https://github.com/ThriftyOldStudent)

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "makefile",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
